# Telegram Bot Token
token = "your_telegram_bot_token_here"

# API 配置
api_key = "your_api_key_here"
embed_api_url = "https://api.siliconflow.cn//v1/embeddings"
embed_model = "BAAI/bge-m3"

# 缓存文件路径
cache_dir = "cache"

# 相似度阈值
similarity_threshold = 0.7  # 可以根据需要调整阈值

# 消息自动删除延迟（秒）
delete_delay = 600  # 10分钟后删除消息

# 消息响应时限（秒）
message_timeout = 300  # 5分钟