# Telegram bot token
token = "YOUR_TELEGRAM_BOT_TOKEN"

# API key for the embedding service
api_key = "YOUR_API_KEY"

# Embedding API URL
embed_api_url = "https://api.example.com/embed"

# Embedding model to use
embed_model = "text-embedding-ada-002"

# Directory to store cached embeddings
cache_dir = "cache"

# Similarity threshold for detecting duplicate messages
similarity_threshold = 0.95

# Delay in seconds before deleting a message identified as a duplicate
delete_delay = 10

# Timeout in seconds for processing messages
message_timeout = 60
